using API_Controller_04_API.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;

namespace API_Controller_04_API.Controllers
{
    //https://code-maze.com/aspnetcore-webapi-best-practices/
    //receives collection
    [Route("api/[controller]")]
    public class DataController : Controller //zamienić na ApiController
    {
        //repository
        private IDataRepository _repository;
        public DataController(IDataRepository repo)
        {
            //repo instance
            _repository = repo;
        }
        /// <summary>
        /// Post some models in DB
        /// </summary>
        /// <description>
        /// Receives a collection of serialized JSON models and stores them in a database created using automated database migrations in console app
        /// </description>
        /// <param name="res">Received collection of models generated by console application</param>
        [HttpPost]
        public void Post([FromBody] List<RequestJSONModel> res)
        {
            //sent data to list
            List<RequestJSONModel> receivedItems = res.ToList();
            //iteration on the list of objects
            for (int i = 0; i < receivedItems.Count(); i++)
            {
                try
                {
                    //parse
                    RequestJSONModel dataItem = new RequestJSONModel
                    {
                        Index = receivedItems[i].Index,
                        Name = receivedItems[i].Name,
                        Visits = receivedItems[i].Visits,
                        Date = receivedItems[i].Date
                    };
                    //calling repo
                    _repository.AddItem(dataItem);
                }
                catch (Exception e)
                {
                    Debug.WriteLine(e);
                }

            }
        }
    }
}
