using System;
using System.Collections.Generic;

namespace List_Comparer
{
    internal class HelperService
    {
        public HelperService() { }

        internal string GetCalendarUrl(string apiKey, DateTime utcNowTimestamp, DateTime utcMonthBackTimestamp, string range = "")
        {
            var dateRange = utcMonthBackTimestamp.Year + "-" + utcMonthBackTimestamp.Month.ToString("00") + "-" + utcMonthBackTimestamp.Day.ToString("00") + "&to=" + utcNowTimestamp.Year + "-" + utcNowTimestamp.Month.ToString("00") + "-" + utcNowTimestamp.Day.ToString("00");

            if (!string.IsNullOrEmpty(range))
            {
                dateRange = range;
            }

            return "https://financialmodelingprep.com/api/v3/economic_calendar?from=" + dateRange + "&apikey=" + apiKey;
        }

        internal Dictionary<string, decimal> GetCountryWeights()
        {
            //https://www.worldometers.info/gdp/gdp-by-country/
            return new Dictionary<string, decimal>()
            {
                { "GB", 0.03M },
                { "FR", 0.028M },
                { "IT", 0.020M },
                { "ES", 0.014M },
                { "CH", 0.008M },
                { "NL", 0.01M },
                { "AT", 0.005M },
                { "NZ", 0.0025M },
                { "FI", 0.0028M },
                { "IE", 0.005M },
                { "GR", 0.0022M },
                { "BG", 0.005M },
                { "PT", 0.0025M },
                { "DE", 0.040M },
                { "CA", 0.0213M },
                { "JP", 0.0421M },
                { "AU", 0.0167M },
                { "US", 0.2532M },
                { "CN", 0.1786M },
                { "PL", 0.0068M },
                { "EC", 0.001M },
                { "EU", 0.15M },
                { "SV", 0.0003M },
                { "LV", 0.0004M },
                { "MT", 0.0002M },
                { "CY", 0.0003M },
                { "BE", 0.0058M },
                { "SI", 0.006M },
                { "LT", 0.007M },
                { "EE", 0.004M },
                { "LU", 0.008M },
                { "ME", 0.0001M },
                { "MX", 0.014M },
                { "BR", 0.0191M },
                { "IN", 0.0337M },
                { "HU", 0.0018M },
                { "SE", 0.0058M },
                { "NO", 0.0058M },
                { "SG", 0.0046M },
                { "TH", 0.0049M },
                { "PH", 0.0040M },
                { "ID", 0.0131M },
                { "CO", 0.0034M },
                { "IL", 0.0052M },
                { "HK", 0.0036M },
                { "CZ", 0.0029M },
                { "DK", 0.0039M },
                { "KR", 0.0166M },
                { "RU", 0.0223M },
                { "ZA", 0.0040M },
            };
        }

        internal Dictionary<string, decimal> GetImpactWeights()
        {
            return new Dictionary<string, decimal>()
            {
                { "High", 1.00M },
                { "Medium", 0.50M },
                { "Low", 0.15M },
            };
        }

        internal Dictionary<string, int> GetEventWeights()
        {
            return new Dictionary<string, int>()
            {
                { "ABSA Manufacturing PMI", 1 },
                { "ADP Employment Change", -1 },
                { "Aggregate Demand QoQ", 1 },
                { "Ai Group Construction Index", 1 },
                { "Ai Group Industry Index", 1 },
                { "Ai Group Manufacturing Index", 1 },
                { "AIB Manufacturing PMI", 1 },
                { "AIB Services PMI", 1 },
                { "ANZ Business Confidence", 1 },
                { "ANZ Roy Morgan Consumer Confidence", 1 },
                { "ANZ-Indeed Job Ads MoM", 1 },
                { "Auto Exports YoY", 1 },
                { "Auto Production YoY", 1 },
                { "Average Hourly Earnings MoM", 1 },
                { "Bank Austria Manufacturing PMI", 1 },
                { "Bank Lending", 1 },
                { "Bank Lending MoM", 1 },
                { "Bank Loan Growth YoY", 1 },
                { "BoC Interest Rate Decision", 1 },
                { "BoE Consumer Credit", 1 },
                { "BoE Interest Rate Decision", 1 },
                { "BoJ Interest Rate Decision", 1 },
                { "BRC Retail Sales Monitor YoY", 1 },
                { "BSI Large Manufacturing QoQ", 1 },
                { "Building Permits", 1 },
                { "Building Permits MoM", 1 },
                { "Business Climate Indicator", 1 },
                { "Business Confidence", 1 },
                { "Business Inventories MoM", -1 },
                { "Business Investment QoQ", 1 },
                { "Business NZ PMI", 1 },
                { "Caixin Composite PMI", 1 },
                { "Caixin Manufacturing PMI", 1 },
                { "Caixin Services PMI", 1 },
                { "Capital Spending YoY", 1 },
                { "Car Production MoM", 1 },
                { "Car Sales YoY", 1 },
                { "CB Consumer Confidence", 1 },
                { "CB Leading Index MoM", 1 },
                { "CBI Industrial Trends Orders", 1 },
                { "Cement Production YoY", 1 },
                { "CFIB Business Barometer", 1 },
                { "Challenger Job Cuts", -1 },
                { "Chicago PMI", 1 },
                { "CNB Interest Rate Decision", 1 },
                { "Commodity Prices YoY", 1 },
                { "Company Gross Profits QoQ", 1 },
                { "Composite Economic Index MoM", 1 },
                { "Construction Orders YoY", 1 },
                { "Construction Output YoY", 1 },
                { "Construction PMI", 1 },
                { "Construction Spending MoM", 1 },
                { "Construction Work Done QoQ", 1 },
                { "Consumer Confidence", 1 },
                { "Consumer Credit Change", 1 },
                { "Consumer Price Index CPI", 1 },
                { "Corporate Profits", 1 },
                { "Corporate Profits QoQ", 1 },
                { "Corporate Sector Wages YoY", 1 },
                { "CPI", 1 },
                { "CPI Median YoY", 1 },
                { "CPI s.a", 1 },
                { "CPI Trimmed-Mean YoY", 1 },
                { "CPIF MoM", 1 },
                { "Credit Card Spending YoY", 1 },
                { "Davivienda Manufacturing PMI", 1 },
                { "DNB Manufacturing PMI", 1 },
                { "Durable Goods Orders MoM", 1 },
                { "ECB Consumer Expectations Survey", 1 },
                { "ECB Economic Projections", 1 },
                { "ECB Interest Rate Decision", 1 },
                { "Economic Activity MoM", 1 },
                { "Economic Sentiment", 1 },
                { "Economic Sentiment Index", 1 },
                { "Electronic Retail Card Spending MoM", 1 },
                { "Employed Persons", 1 },
                { "Employment Change", 1 },
                { "Employment Change QoQ", 1 },
                { "Existing Home Sales", -1 },
                { "Existing Home Sales MoM", -1 },
                { "Export Orders YoY", 1 },
                { "Exports", 1 },
                { "Exports MoM", 1 },
                { "Factory Orders MoM", 1 },
                { "Fed Interest Rate Decision", 1 },
                { "FGV Consumer Confidence", 1 },
                { "Fixed Asset Investment (YTD) YoY", 1 },
                { "FOMC Economic Projections", 1 },
                { "Foreign Direct Investment", 1 },
                { "GDP Growth Rate QoQ", 1 },
                { "GDP Growth Rate QoQ Adv", 1 },
                { "GDP MoM", 1 },
                { "GDP YoY", 1 },
                { "Gfk Consumer Confidence", 1 },
                { "Halifax House Price Index MoM", 1 },
                { "HALPIM Manufacturing PMI", 1 },
                { "Harmonised Inflation Rate MoM", 1 },
                { "HCOB Composite PMI", 1 },
                { "HCOB Construction PMI", 1 },
                { "HCOB Manufacturing PMI", 1 },
                { "HCOB Services PMI", 1 },
                { "Home Loans MoM", 1 },
                { "House Price Index", 1 },
                { "House Price Index MoM", 1 },
                { "Household Consumption MoM", 1 },
                { "Household Spending MoM", 1 },
                { "Housing Credit MoM", 1 },
                { "Housing Starts", 1 },
                { "Housing Starts MoM", 1 },
                { "IBC-BR Economic Activity", 1 },
                { "IBD/TIPP Economic Optimism", 1 },
                { "Ifo Business Climate", 1 },
                { "Ifo Current Conditions", 1 },
                { "Ifo Expectations", 1 },
                { "Imports", 1 },
                { "Imports MoM", 1 },
                { "Industrial Production MoM", 1 },
                { "Industrial Production MoM.", 1 },
                { "Industrial Sales MoM", 1 },
                { "Industrial Sentiment", 1 },
                { "Inflation Expectations", 1 },
                { "Inflation Rate MoM", 1 },
                { "Interest Rate Decision", 1 },
                { "Investment Lending for Homes", 1 },
                { "IPCA mid-month CPI MoM", 1 },
                { "IPC-Fipe Inflation MoM", 1 },
                { "ISE Economic Activity YoY", 1 },
                { "ISM Manufacturing Employment", 1 },
                { "ISM Manufacturing New Orders", 1 },
                { "ISM Manufacturing PMI", 1 },
                { "ISM Manufacturing Prices", 1 },
                { "ISM Non-Manufacturing Business Activity", 1 },
                { "ISM Non-Manufacturing Employment", 1 },
                { "ISM Non-Manufacturing New Orders", 1 },
                { "ISM Non-Manufacturing PMI", 1 },
                { "ISM Non-Manufacturing Prices", 1 },
                { "ISM Services Business Activity", 1 },
                { "ISM Services Employment", 1 },
                { "ISM Services New Orders", 1 },
                { "ISM Services PMI", 1 },
                { "ISM Services Prices", 1 },
                { "Ivey PMI s.a", 1 },
                { "Jibun Bank Composite PMI", 1 },
                { "Jibun Bank Manufacturing PMI", 1 },
                { "Jibun Bank Services PMI", 1 },
                { "Judo Bank Composite PMI", 1 },
                { "Judo Bank Manufacturing PMI", 1 },
                { "Judo Bank Services PMI", 1 },
                { "KOF Leading Indicators", 1 },
                { "Leading Economic Index", 1 },
                { "Lending Facility Rate", 1 },
                { "LMI Logistics Managers Index Current", 1 },
                { "Loan Growth YoY", 1 },
                { "Loan Officer Survey", 1 },
                { "Loan Prime Rate 1Y", 1 },
                { "Loan Prime Rate 5Y", 1 },
                { "Loans to Companies YoY", 1 },
                { "Loans to Households YoY", 1 },
                { "M1 Money Supply YoY", 1 },
                { "M2 Money Supply YoY", 1 },
                { "M3 Money Supply YoY", 1 },
                { "M4 Money Supply MoM", 1 },
                { "Machine Tool Orders YoY", 1 },
                { "Machinery Orders MoM", 1 },
                { "Manufacturing PMI", 1 },
                { "Manufacturing Production MoM", 1 },
                { "Manufacturing Sales MoM", 1 },
                { "MBA Mortgage Applications", 1 },
                { "MBA Mortgage Market Index", 1 },
                { "MBA Mortgage Refinance Index", 1 },
                { "MBA Purchase Index", 1 },
                { "Michigan Consumer Expectations", 1 },
                { "Michigan Consumer Sentiment", 1 },
                { "Michigan Current Conditions", 1 },
                { "Mid-month Core Inflation Rate MoM", 1 },
                { "Mid-month Inflation Rate MoM", 1 },
                { "Mining Production MoM", 1 },
                { "Money Supply M3", 1 },
                { "Monthly CPI Indicator", 1 },
                { "Mortgage Approvals", 1 },
                { "Mortgage Lending", 1 },
                { "Motorbike Sales YoY", 1 },
                { "NAB Business Confidence", 1 },
                { "NAHB Housing Market Index", 1 },
                { "Nationwide Housing Prices MoM", 1 },
                { "NBS General PMI", 1 },
                { "NBS Manufacturing PMI", 1 },
                { "NBS Non Manufacturing PMI", 1 },
                { "Net Lending to Individuals MoM", 1 },
                { "NEVI Manufacturing PMI", 1 },
                { "New Car Registrations MoM", 1 },
                { "New Car Sales YoY", 1 },
                { "New Home Sales", 1 },
                { "New Home Sales MoM", 1 },
                { "New Housing Price Index MoM", 1 },
                { "New Motor Vehicle Sales", 1 },
                { "New Orders YoY", 1 },
                { "New Yuan Loans", 1 },
                { "NFIB Business Optimism Index", 1 },
                { "NIESR Monthly GDP Tracker", 1 },
                { "Non-Oil Exports MoM", 1 },
                { "Norges Bank Interest Rate Decision", 1 },
                { "OECD Economic Outlook", 1 },
                { "Outstanding Loan Growth YoY", -1 },
                { "Passenger Vehicles Sales YoY", 1 },
                { "PCE Price Index MoM", 1 },
                { "Pending Home Sales MoM", -1 },
                { "Personal Income (MoM)", 1 },
                { "Personal Income MoM", 1 },
                { "Personal Spending MoM", 1 },
                { "Plant Machinery Capital Expenditure QoQ", 1 },
                { "PPI Core Output MoM", 1 },
                { "PPI Input MoM", 1 },
                { "PPI MoM", 1 },
                { "PPI Output MoM", 1 },
                { "Private Capital Expenditure QoQ", 1 },
                { "Private Consumption MoM", 1 },
                { "Private House Approvals MoM", 1 },
                { "Private Investment MoM", 1 },
                { "Private Sector Credit MoM", 1 },
                { "procure.ch Manufacturing PMI", 1 },
                { "Producer & Import Prices MoM", 1 },
                { "Property Price Index YoY", 1 },
                { "Public Sector Net Borrowing", 1 },
                { "Raw Materials Prices MoM", 1 },
                { "RBA Interest Rate Decision", 1 },
                { "RBI Interest Rate Decision", 1 },
                { "RBNZ Interest Rate Decision", 1 },
                { "RCM/TIPP Economic Optimism Index", 1 },
                { "Real Consumer Spending QoQ", 1 },
                { "Real Wage Growth YoY", 1 },
                { "Real Wages YoY", 1 },
                { "Redbook YoY", 1 },
                { "Residential Property Prices MoM", 1 },
                { "Retail Price Index MoM", 1 },
                { "Retail Sales MoM", 1 },
                { "Riksbank Rate Decision", 1 },
                { "S&P Global Composite PMI", 1 },
                { "S&P Global Construction PMI", 1 },
                { "S&P Global Manufacturing PMI", 1 },
                { "S&P Global PMI", 1 },
                { "S&P Global Services PMI", 1 },
                { "S&P Global/CIPS Composite PMI", 1 },
                { "S&P Global/CIPS Construction PMI", 1 },
                { "S&P Global/CIPS Manufacturing PMI", 1 },
                { "S&P Global/CIPS Services PMI", 1 },
                { "S&P Global/CIPS UK Services PMI", 1 },
                { "S&P/Case-Shiller Home Price MoM", 1 },
                { "SACCI Business Confidence", 1 },
                { "SECO Economic Forecasts", 1 },
                { "Selling Price Expectations", 1 },
                { "Senior Loan Officer Survey", 1 },
                { "Services PMI", 1 },
                { "Services Sentiment", 1 },
                { "SIPMM Manufacturing PMI", 1 },
                { "SNB Interest Rate Decision", 1 },
                { "Stock Investment by Foreigners", 1 },
                { "Swedbank Manufacturing PMI", 1 },
                { "Tankan Large All Industry Capex", 1 },
                { "Tankan Large Manufacturers Index", 1 },
                { "Tankan Large Manufacturing Outlook", 1 },
                { "Tankan Large Non-Manufacturing Index", 1 },
                { "Tankan Non-Manufacturing Outlook", 1 },
                { "Tankan Small Manufacturers Index", 1 },
                { "TD-MI Inflation Gauge MoM", 1 },
                { "Tertiary Industry Index MoM", 1 },
                { "Tokyo Core CPI YoY", -1 },
                { "Tokyo CPI YoY", -1 },
                { "Total Credit YoY", 1 },
                { "Total Household Debt", 1 },
                { "Total New Vehicle Sales", 1 },
                { "Total Social Financing", 1 },
                { "Total Vehicle Sales", 1 },
                { "Tourist Arrivals YoY", 1 },
                { "Unemployment Rate", -1 },
                { "Used Car Prices MoM", 1 },
                { "Vehicle Sales YoY", 1 },
                { "Visitor Arrivals YoY", 1 },
                { "Wage Growth YoY", 1 },
                { "Westpac Consumer Confidence", 1 },
                { "Westpac Leading Index MoM", 1 },
                { "Wholesale Prices MoM", 1 },
                { "Wholesale Sales MoM", 1 },
                { "WPI Inflation YoY", 1 },
                { "WPI Manufacturing YoY", 1 },
                { "ZEW Current Conditions", 1 },
                { "ZEW Economic Sentiment Index", 1 },
            };
        }
        
        /*internal Dictionary<string, int> GetEventWeights()
        {
            return new Dictionary<string, int>()
            {
                { "ADP Employment Change", 1 },
                { "AIB Manufacturing PMI", 1 },
                { "AIB Services PMI", 1 },
                { "ANZ Business Confidence", 1 },
                { "ANZ Roy Morgan Consumer Confidence", 1 },
                { "Average Earnings excl. Bonus", 1 },
                { "Average Earnings incl. Bonus", 1 },
                { "Average Hourly Earnings MoM", 1 },
                { "Average Hourly Earnings YoY", 1 },
                { "Average Hourly Wages YoY", 1 },
                { "Average Weekly Earnings YoY", 1 },
                { "Average Weekly Hours", 1 },
                { "Baden Wuerttemberg CPI MoM", -1 },
                { "Baden Wuerttemberg CPI YoY", -1 },
                { "Bank Austria Manufacturing PMI", 1 },
                { "Bank Lending YoY", 1 },
                { "Bavaria CPI MoM", -1 },
                { "Bavaria CPI YoY", -1 },
                { "BBA Mortgage Rate", -1 },
                { "BoE Consumer Credit", 1 },
                { "BoE Interest Rate Decision", -1 },
                { "Brandenburg CPI MoM", -1 },
                { "Brandenburg CPI YoY", -1 },
                { "BRC Retail Sales Monitor YoY", 1 },
                { "Building Permits", 1 },
                { "Building Permits MoM", 1 },
                { "Building Permits YoY", 1 },
                { "Business Confidence", 1 },
                { "Business Inflation Expectations", -1 },
                { "Business Inventories MoM", -1 },
                { "Business Investment QoQ", 1 },
                { "Business Investment YoY", 1 },
                { "Business NZ PMI", 1 },
                { "Caixin Composite PMI", 1 },
                { "Caixin Manufacturing PMI", 1 },
                { "Caixin Services PMI", 1 },
                { "Capital Spending YoY", 1 },
                { "Car Production YoY", 1 },
                { "CB Consumer Confidence", 1 },
                { "Chicago PMI", 1 },
                { "Claimant Count Change", -1 },
                { "Construction Orders YoY", 1 },
                { "Construction Output YoY", 1 },
                { "Construction PMI", 1 },
                { "Construction Spending MoM", 1 },
                { "Construction Work Done QoQ", 1 },
                { "Consumer Confidence", 1 },
                { "Consumer Credit Change", 1 },
                { "Consumer Inflation Expectations", -1 },
                { "Continuing Jobless Claims", -1 },
                { "Core Inflation Rate MoM", -1 },
                { "Core Inflation Rate YoY", -1 },
                { "Core PCE Price Index MoM", -1 },
                { "Core PCE Price Index YoY", -1 },
                { "Core PCE Prices QoQ", -1 },
                { "Core PPI MoM", -1 },
                { "Core PPI YoY", -1 },
                { "Corporate Profits QoQ", 1 },
                { "CPI Median YoY", -1 },
                { "CPI s.a", -1 },
                { "CPI Trimmed-Mean YoY", -1 },
                { "Credit Card Spending YoY", 1 },
                { "Dallas Fed Manufacturing Index", 1 },
                { "Dallas Fed Services Index", 1 },
                { "Dallas Fed Services Revenues Index", 1 },
                { "Durable Goods Orders ex Defense MoM", 1 },
                { "Durable Goods Orders Ex Transp MoM", 1 },
                { "Durable Goods Orders MoM", 1 },
                { "ECB Interest Rate Decision", -1 },
                { "Electronic Retail Card Spending MoM", 1 },
                { "Electronic Retail Card Spending YoY", 1 },
                { "Existing Home Sales", -1 },
                { "Existing Home Sales MoM", -1 },
                { "Export Prices MoM", 1 },
                { "Export Prices QoQ", 1 },
                { "Export Prices YoY", 1 },
                { "Factory Orders ex Transportation", 1 },
                { "Factory Orders MoM", 1 },
                { "Fed Interest Rate Decision", -1 },
                { "Food Inflation YoY", -1 },
                { "GDP 3-Month Avg", 1 },
                { "GDP Capital Expenditure QoQ", 1 },
                { "GDP External Demand QoQ", 1 },
                { "GDP Growth Annualized", 1 },
                { "GDP Growth Rate Annualized", 1 },
                { "GDP Growth Rate QoQ", 1 },
                { "GDP Growth Rate YoY", 1 },
                { "GDP Implicit Price QoQ", 1 },
                { "GDP MoM", 1 },
                { "GDP Price Index QoQ", 1 },
                { "GDP Price Index YoY", 1 },
                { "GDP Private Consumption QoQ", 1 },
                { "GDP Sales QoQ", 1 },
                { "GDP YoY", 1 },
                { "Halifax House Price Index MoM", 1 },
                { "Halifax House Price Index YoY", 1 },
                { "Harmonised Inflation Rate MoM", -1 },
                { "Harmonised Inflation Rate YoY", -1 },
                { "Hesse CPI MoM", -1 },
                { "Hesse CPI YoY", -1 },
                { "Home Loans MoM", 1 },
                { "House Price Index", 1 },
                { "House Price Index MoM", 1 },
                { "House Price Index YoY", 1 },
                { "Household Consumption MoM", 1 },
                { "Household Consumption YoY", 1 },
                { "Household Spending MoM", 1 },
                { "Household Spending YoY", 1 },
                { "Housing Credit MoM", 1 },
                { "Housing Starts", 1 },
                { "Housing Starts MoM", 1 },
                { "Housing Starts YoY", 1 },
                { "IBD/TIPP Economic Optimism", 1 },
                { "Ifo Business Climate", 1 },
                { "Ifo Current Conditions", 1 },
                { "Ifo Expectations", 1 },
                { "Import Prices MoM", -1 },
                { "Import Prices QoQ", -1 },
                { "Import Prices YoY", -1 },
                { "Industrial Production MoM", 1 },
                { "Industrial Production YoY", 1 },
                { "Industrial Profits", 1 },
                { "Industrial Sales MoM", 1 },
                { "Industrial Sales YoY", 1 },
                { "Industrial Sentiment", 1 },
                { "Inflation Rate Ex-Food and Energy YoY", -1 },
                { "Inflation Rate MoM", -1 },
                { "Inflation Rate YoY", -1 },
                { "Initial Jobless Claims", -1 },
                { "Investment Lending for Homes", 1 },
                { "ISM Manufacturing Employment", 1 },
                { "ISM Manufacturing New Orders", 1 },
                { "ISM Manufacturing PMI", 1 },
                { "ISM Manufacturing Prices", 1 },
                { "ISM Non-Manufacturing Business Activity", 1 },
                { "ISM Non-Manufacturing Employment", 1 },
                { "ISM Non-Manufacturing New Orders", 1 },
                { "ISM Non-Manufacturing PMI", 1 },
                { "ISM Non-Manufacturing Prices", 1 },
                { "Jibun Bank Composite PMI", 1 },
                { "Jibun Bank Manufacturing PMI", 1 },
                { "Jibun Bank Services PMI", 1 },
                { "Jobless Claims 4-week Average", -1 },
                { "Jobs/applications ratio", -1 },
                { "Jobseekers Total", -1 },
                { "JOLTs Job Openings", 1 },
                { "JOLTs Job Quits", -1 },
                { "Judo Bank Composite PMI", 1 },
                { "Judo Bank Manufacturing PMI", 1 },
                { "Judo Bank Services PMI", 1 },
                { "Kansas Fed Composite Index", 1 },
                { "Kansas Fed Manufacturing Index", 1 },
                { "Leading Economic Index", 1 },
                { "LMI Logistics Managers Index Current", 1 },
                { "Loan Officer Survey", 1 },
                { "Loans to Companies YoY", 1 },
                { "Loans to Households YoY", 1 },
                { "M2 Money Supply YoY", 1 },
                { "M3 Money Supply YoY", 1 },
                { "Machine Tool Orders YoY", 1 },
                { "Machinery Orders MoM", 1 },
                { "Machinery Orders YoY", 1 },
                { "Manufacturing Payrolls", 1 },
                { "Manufacturing Production MoM", 1 },
                { "Manufacturing Production YoY", 1 },
                { "Manufacturing Sales MoM", 1 },
                { "MBA Mortgage Applications", 1 },
                { "MBA Mortgage Market Index", 1 },
                { "MBA Mortgage Refinance Index", 1 },
                { "MBA Purchase Index", 1 },
                { "Michigan 5 Year Inflation Expectations", -1 },
                { "Michigan Consumer Expectations", 1 },
                { "Michigan Consumer Sentiment", 1 },
                { "Michigan Current Conditions", 1 },
                { "Michigan Inflation Expectations", -1 },
                { "Monthly CPI Indicator", -1 },
                { "Mortgage Approvals", 1 },
                { "Mortgage Lending", 1 },
                { "NAB Business Confidence", 1 },
                { "NAHB Housing Market Index", 1 },
                { "Nationwide Housing Prices MoM", 1 },
                { "Nationwide Housing Prices YoY", 1 },
                { "NBS General PMI", 1 },
                { "NBS Manufacturing PMI", 1 },
                { "NBS Non Manufacturing PMI", 1 },
                { "Net Lending to Individuals MoM", 1 },
                { "Net Long-term TIC Flows", 1 },
                { "NEVI Manufacturing PMI", 1 },
                { "New Car Registrations YoY", 1 },
                { "New Car Sales YoY", 1 },
                { "New Home Sales", 1 },
                { "New Home Sales MoM", 1 },
                { "New Housing Price Index MoM", 1 },
                { "New Housing Price Index YoY", 1 },
                { "New Motor Vehicle Sales", 1 },
                { "NFIB Business Optimism Index", 1 },
                { "NIESR Monthly GDP Tracker", 1 },
                { "Non Defense Goods Orders Ex Air", 1 },
                { "Nonfarm Productivity QoQ", 1 },
                { "North Rhine Westphalia CPI MoM", -1 },
                { "North Rhine Westphalia CPI YoY", -1 },
                { "NY Empire State Manufacturing Index", 1 },
                { "Outstanding Loan Growth YoY", -1 },
                { "Overall Net Capital Flows", 1 },
                { "Overtime Pay YoY", 1 },
                { "Part Time Employment Chg", 1 },
                { "PCE Price Index MoM", -1 },
                { "PCE Price Index YoY", -1 },
                { "PCE Prices QoQ", -1 },
                { "Pending Home Sales MoM", 1 },
                { "Pending Home Sales YoY", 1 },
                { "Personal Income MoM", 1 },
                { "Personal Spending MoM", 1 },
                { "Philadelphia Fed Manufacturing Index", 1 },
                { "Philly Fed Business Conditions", 1 },
                { "Philly Fed CAPEX Index", 1 },
                { "Philly Fed Employment", 1 },
                { "Plant Machinery Capital Expenditure QoQ", 1 },
                { "PPI Core Output MoM", -1 },
                { "PPI Core Output YoY", -1 },
                { "PPI Input MoM", -1 },
                { "PPI Input QoQ", -1 },
                { "PPI Input YoY", -1 },
                { "PPI MoM", -1 },
                { "PPI Output MoM", -1 },
                { "PPI Output QoQ", -1 },
                { "PPI Output YoY", -1 },
                { "PPI YoY", -1 },
                { "Private Capital Expenditure QoQ", 1 },
                { "Private Consumption YoY", 1 },
                { "Private House Approvals MoM", 1 },
                { "Private Non Farm Payrolls QoQ", 1 },
                { "Private Sector Credit MoM", 1 },
                { "Private Sector Credit YoY", 1 },
                { "procure.ch Manufacturing PMI", 1 },
                { "Producer & Import Prices MoM", -1 },
                { "Producer & Import Prices YoY", -1 },
                { "Public Sector Net Borrowing", 1 },
                { "Public Sector Net Borrowing Ex Banks", 1 },
                { "Raw Materials Prices MoM", -1 },
                { "Raw Materials Prices YoY", -1 },
                { "RBA Interest Rate Decision", -1 },
                { "RBNZ Interest Rate Decision", -1 },
                { "Real Consumer Spending QoQ", 1 },
                { "Redbook YoY", 1 },
                { "Residential Property Prices MoM", 1 },
                { "Residential Property Prices YoY", 1 },
                { "Retail Inventories Ex Autos MoM", -1 },
                { "Retail Price Index MoM", -1 },
                { "Retail Price Index YoY", -1 },
                { "Retail Sales Ex Autos MoM", 1 },
                { "Retail Sales ex Fuel MoM", 1 },
                { "Retail Sales ex Fuel YoY", 1 },
                { "Retail Sales Ex Gas/Autos MoM", 1 },
                { "Retail Sales MoM", 1 },
                { "Retail Sales QoQ", 1 },
                { "Retail Sales YoY", 1 },
                { "Richmond Fed Manufacturing Index", 1 },
                { "Richmond Fed Manufacturing Shipments Index", 1 },
                { "Richmond Fed Services Index", 1 },
                { "RICS House Price Balance", 1 },
                { "S&P Global Composite PMI", 1 },
                { "S&P Global Construction PMI", 1 },
                { "S&P Global Manufacturing PMI", 1 },
                { "S&P Global Services PMI", 1 },
                { "S&P Global/CIPS Composite PMI", 1 },
                { "S&P Global/CIPS Construction PMI", 1 },
                { "S&P Global/CIPS Manufacturing PMI", 1 },
                { "S&P Global/CIPS UK Services PMI", 1 },
                { "S&P/Case-Shiller Home Price MoM", 1 },
                { "S&P/Case-Shiller Home Price YoY", 1 },
                { "Saxony CPI MoM", -1 },
                { "Saxony CPI YoY", -1 },
                { "Selling Price Expectations", -1 },
                { "Senior Loan Officer Survey", 1 },
                { "Services NZ PSI", 1 },
                { "Services Sentiment", 1 },
                { "Stock Investment by Foreigners", 1 },
                { "Tokyo Core CPI YoY", -1 },
                { "Tokyo CPI Ex Food and Energy YoY", -1 },
                { "Tokyo CPI YoY", -1 },
                { "Total Credit YoY", 1 },
                { "Total Social Financing", 1 },
                { "Total Vehicle Sales", 1 },
                { "Tourist Arrivals YoY", 1 },
                { "Unemployed Persons", -1 },
                { "Unemployment Benefit Claims", -1 },
                { "Unemployment Change", -1 },
                { "Unemployment Rate", -1 },
                { "Used Car Prices MoM", 1 },
                { "Used Car Prices YoY", 1 },
                { "Vehicle Sales YoY", 1 },
                { "Visitor Arrivals YoY", 1 },
                { "Westpac Consumer Confidence Change", 1 },
                { "Westpac Consumer Confidence Index", 1 },
                { "Westpac Leading Index MoM", 1 },
                { "Wholesale Inventories MoM", -1 },
                { "Wholesale Prices MoM", -1 },
                { "Wholesale Prices YoY", -1 },
                { "Wholesale Sales MoM", 1 },
                { "ZEW Current Conditions", 1 },
                { "ZEW Economic Sentiment Index", 1 },
            };
        }*/
    }
}
